### ISSUE TITLE
On close event

### ISSUE THREAD

**Issue by probablykasper** [thesbros/gulp-run-electron#8]
I'd like to receive a close event from runElectron. The reason is that when Electron closes, I would like to quit Gulp (so it stops watching for file changes).

**Comment by odensc** [comment]
If you're restarting Electron on file change, the close event would be called every time. Is that okay, or would you only want the event to be called when the user closes Electron?

**Comment by probablykasper** [comment]
Good point. Ideally the event would tell you if it the event comes from restarting or not.

I got this working with [electron-connect](https://www.npmjs.com/package/electron-connect), so if you don't wanna bother, that's cool. My code looks like this:
```js
gulp.task("electron", function () {
    electron.start(((electronProcState) => {
        if (electronProcState == "stopped") {
            process.exit();
        }
    }));

    gulp.watch(reloadPath, function ReloadElectron(done) {
        electron.reload();
        done();
    });
    gulp.watch(restartPath, {}, function restartElectron(done) {
        electron.restart();
        done();
    });

});
```

**Comment by odensc** [comment]
Yeah, I think I'd like to keep this plugin simple. Thanks for the suggestion though!
